# Generated by Django 5.0.2 on 2024-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_pw_change',
            field=models.BooleanField(default=False),
        ),
    ]
