# Generated by Django 5.0.2 on 2024-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
