# Generated by Django 5.0.2 on 2024-03-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lecture_type', models.CharField(choices=[('lecture', 'Lecture'), ('practical', 'Practical'), ('workshop', 'Workshop'), ('exam', 'Exam')], default='lecture')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lecture', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='AttendenceAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_student', models.BooleanField(default=False)),
                ('attended_teacher', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ack', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='api.courselecture')),
            ],
        ),
    ]
