# Generated by Django 5.0.2 on 2024-03-14 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_courselecture_attendenceacknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendenceacknowledgement',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_ack', to='api.courselecture'),
        ),
    ]
