# Generated by Django 5.0.2 on 2024-03-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_attendenceacknowledgement_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
    ]
