# Generated by Django 5.0.2 on 2024-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_course_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendenceacknowledgement',
            name='attended_student',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendenceacknowledgement',
            name='attended_teacher',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
