name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup up Requirements
      run: |
        source venv/bin/activate
        chmod +x ./getEnv.sh && ./getEnv.sh
        python load_env.py
        zappa package prod -o package.zip

    - name: Deploy
      run: |
        cd deployments
        terraform init
        terraform apply -auto-approve
